### PR TITLE
Authors out of order based on list stored in the database, fixes issue #335

### PR DESCRIPTION
**Pull request by mwharrison**
The authors are out of order based on the list in the database.
Implemented index based array sorting in the sql. Updated existing
tests to match new return order (coverage is acceptable).

### CODE REVIEW

**Comment by reedstrm** [comment]
For devops purposes, it's important to note that this is a schema (adding the function def) Ideally, include the commands necessary to bring a DB up-to-date is nice. In this case:

**Comment by rich-hart** [comment]
I see that some of the ``CONTENT_METADATA`` fields were changed in the ``test_view.py`` unit tests, but its not clear to me which specific test is being used to insure the ordering of authors.   Would mind mentioning which test demonstrates the behavior your looking for?

**Comment by mwharrison** [comment]
test_collection_content will fail if the authors are returned out of order

**Comment by rich-hart** [comment]
Looks good then.  Merging...

**Pull request merged**
