### PR TITLE
One content route and cache control on that route

### PR DESCRIPTION
**Pull request by reedstrm**
This code merges the content* routes, so we can handle cache-control in one place.

### CODE REVIEW

**Comment by pumazi** [comment]
I can't say I'm in agreement with this changeset. Instead of letting the framework do the work, we've taken it upon ourselves to do routing logic in the view.

**Comment by reedstrm** [comment]
I'd say rather than hiding complex routing logic in the framework in three different methods across two files, requiring comparing 3 regexes by eye, we're drying out route implementation to allow using the framework for view configuration  - i.e. default cache behavior, and placing the not-obvious routing and cache-override logic on one place with comments.

TBH, I've never like the magic-file-extension-to-change-returned-data routes anyway: HTTP  has a way to specify wanting different types: the accepted-types header. But we're using it, so leaving in place.

**Comment by reedstrm** [comment]
Seems I had the regex slightly wrong. Kudos to everyone who's contributed to the extensive set of route and content tests: caught a couple coding errors here.

**Comment by reedstrm** [comment]
@pumazi Let me clarify the comment re: doing routing in the logic. Currently, there are _two_ ways to select html vs json return type: one is to set an `Accept:` header, that we processed in the `content` route and view: the other is to append ".html" or ".json", which then is matched to either `content-html` or `content-json` views. So there are 3 views associated with 3 routes to serve two different `Content-Type` returns. Which means to do anything with caching consistently across all `/contents` urls requires repeating something three times. This PR collapses the 3 routes to 1, and combines the `Content-Type` selection logic that was otherwise spread between 3 views into one place. It then applies a default caching policy via the framework tools  (view_config parameter) and uses logic in that one view to override for content-specific reasons (baking-in-flight-or-errored). It was while repeating that caching override logic in two places (and about to add the third place) that drove me to do this refactor, instead.

**Pull request merged**
