### PR TITLE
Html tree depth

### PR DESCRIPTION
**Pull request by reedstrm**
Mixed PR, I'm afraid. Alter html form of a book to expose the depth-of-nesting (in lieu of chapter/unit/etc.) Also, add some tests to in-book-search.

### CODE REVIEW

**Comment by karenc** [comment]
I got more in-book-search fixes in the first 4 commits of #394.  Maybe I'll remove the other commits so that can be merged.

**Comment by reedstrm** [comment]
I'll rebase this to just the html part.

**Comment by pumazi** [comment]
What's the basis for needing the ``data-depth`` attribute on these tags?

Seems like you could get this info in CSS and XPath without explicitly defining it. Also, this html isn't used anywhere except in the archive html view. Are you using this somewhere else?

**Comment by pumazi** [comment]
Now that cnx-archive depends on cnx-epub we can move this logic there. There is actually a copy of these functions within the adapters module.

**Comment by reedstrm** [comment]
As we discussed in a meeting, this change is on the path toward assembling a nested-html to represent a full book (nodes _and_ leaves). That's probably going to take other code, since we can't just include the page html files (can't nest <html> or <body> tags), so some processing will be needed.
I'm still thinking that it's within archive portfolio to provide it. Perhaps publish should push a 'div-ified' version of each page as well, for this use case.

BTW,  depth-of-nesting is actually somewhat tricky to do with CSS or XPATH. Full-on XSLT has a count() function that could serve, but we're trying to remove XSLT from the pipeline.

Closing, as not currently in scope.

**Pull request closed without merging**
