### PR TITLE
Move the file trigger update to a separate migration

### PR DESCRIPTION
**Pull request by karenc**
It makes things easier because migrations that are already run on a
server should not really be changed.

### CODE REVIEW

**Comment by reedstrm** [comment]
to reify my comment from the meeting - I think this is true, that migrations that have been run _on a production server_ should never be changed. But dev doesn't count (qa probably not, even)

**Comment by karenc** [comment]
I disagree. I think unless a migration is wrong, we should just leave it alone.

**Comment by Dantemss** [comment]
It all depends how important the data in dev is... if you are fine with totally dropping the dev DB then migrations that ran in dev don't matter :)

**Comment by reedstrm** [comment]
Not being able to complete on production in a reasonable amount of time makes it wrong, in my book. That's the ops half of devops. That's also why this PR splitting the trigger changes out to a separate migration is exactly right - dropping/adding triggers is _much_ riskier in a production environment - depending on the load, it can stall essentially forever.

**Pull request merged**
