### PR TITLE
Publish to legacy transforms

### PR DESCRIPTION
**Pull request by pumazi**
Includes changes to the existing triggers, which will allow them to also do html5->cnxml transforms.

Detailed list of the changes:
* function to utilize rhaptos.cnxmlutils XSLT for html5->cnxml
* revised trigger for module_files
* *new* reference resolver for html urls
* refactored transform code (organized by converters, producers and resolvers)
* deprecated sql functions for html->cnxml
* *new* sql functions for html->cnxml and cnxml->html

Depends on structural changes (for outer wrapping tags) in Connexions/rhaptos.cnxmlutils#80

See also [the trello card](https://trello.com/c/SDB801FO/1062-13-implement-rewrite-to-legacy-publishing)

### CODE REVIEW

**Comment by karenc** [comment]
I've made some changes to Connexions/rhaptos.cnxmlutils#80, when I ran the archive test with the updated cnxmlutils, one test failed:

```
======================================================================
FAIL: test_reference_rewrites (cnxarchive.tests.transforms.test_resolvers.CnxmlReferenceResolutionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cnxarchive/tests/testing.py", line 70, in wrapped
    return method(self, cursor, *args, **kwargs)
  File "cnxarchive/tests/transforms/test_resolvers.py", line 408, in test_reference_rewrites
    namespaces=nsmap)[0]))
AssertionError: 'thumbnail="Figure_01_00_01.jpg"' not found in '<media xmlns="http://cnx.rice.edu/cnxml" xmlns:md="http://cnx.rice.edu/mdml/0.4" xmlns:md1="http://cnx.rice.edu/mdml" xmlns:bib="http://bibtexml.sf.net/" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:q="http://cnx.rice.edu/qml/1.0" alt="alternate" id="image-w-thumbnail">\n    <para class="not-converted-yet">NOT_CONVERTED_YET: span</para><span xmlns="http://www.w3.org/1999/xhtml" media-type="image/png" print="true" src="../resources/d47864c2ac77d80b1f2ff4c4c7f1b2059669e3e9/mass-sprint-lab_en.jar" thumbnail="../resources/d47864c2ac77d80b1f2ff4c4c7f1b2059669e3e9" width="450"/>\n  </media>\n\n\n\n  '
```

Is it because I changed the cnxmlutils code or my local setup is incorrect maybe?

**Comment by pumazi** [comment]
@karenc Try running the tests again with my recent changes. They shouldn't necessarily be related to the failure you are seeing.

I'm seeing all tests pass after pulling the most recent changes to rhaptos.cnxmlutils.

**Comment by pumazi** [comment]
Note, **Please run cnx-publishing and cnx-authoring tests locally before accepting/merging this code.**

**Comment by karenc** [comment]
The system python on travis is version 2.7.3 and it considers the following regular expression invalid, the error says "sre_constants.error: nothing to repeat":

```python
PATH_REFERENCE_REGEX = re.compile(r"""
^(?:
  (https?://cnx.org)
  |
  (?P<legacy>https?://legacy.cnx.org)
  )?
(?:
  /contents/
  (?P<document>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})
  (?:  @  (?P<version>[.\d]+)  )?
  (?:
    :
    (?P<bound_document>[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}
      (  @  \d+  )?
      )?
    )?
  )?
(?: ([.]{2})?/resources/
  (?P<resource>[0-9a-f]{40})?
  )?
(?P<fragment>.*)?
""", re.IGNORECASE|re.VERBOSE)
```

I've downloaded python 2.7.3 and I could reproduce the error.  An easy way to fix this is to change the second to last line from `(?P<fragment>.*)?` to `(?P<fragment>.+)?`.  That's the "nothing to repeat" error.

@pumazi you want to try this?

**Comment by pumazi** [comment]
There appears to be one legitimate failure happening. It turns out one of the element transforms is not in Connexions/rhaptos.cnxmlutils#80 which is causing one of the reference resolution tests to fail. @karenc is working on fixing this.

See also [Travis-CI build 49477615](https://travis-ci.org/Connexions/cnx-archive/builds/49477615) which include the dependent branch when running the tests.

**Comment by rich-hart** [comment]
Karen's latest push to Connexions/rhaptos.cnxmlutils#80 fixed the Fails I was having on my machine

**Comment by karenc** [comment]
It's also fixed on travis: https://travis-ci.org/Connexions/cnx-archive/builds/49477615

**Comment by karenc** [comment]
Do we need to change legacy to look for `index.html.cnxml` if `index.cnxml` doesn't exist?

**Comment by reedstrm** [comment]
Hmm, there are on the order of 90 references to index.cnxml in the legacy code base. This is all new publish, so there's no danger of collision - I think we should create index.cnxml, probably in addition to the index.html.cnxml. It's just one more link in module_files table.

**Comment by pumazi** [comment]
When deploying and testing, make sure you pull changes for our fork of http://github.com/Connexions/plpydbapi.

**Comment by pumazi** [comment]
The latest commit addressed your ( @karenc and @reedstrm ) comments about the index.cnxml. This now inserts two module_files entries, one for our flag file 'index.html.cnxml' and the usual 'index.cnxml'. It uses the same file table entry (as I'm sure you expected).

**Pull request merged**
