### PR TITLE
Move transforms to cnx-db

### PR DESCRIPTION
**Pull request by pumazi**
These changes are in response to Connexions/cnx-db#86. This removes the transforms from this package and places them in cnx-db.

### CODE REVIEW

**Comment by pumazi** [comment]
@karenc, sorry to say but your fix in #539 might have a glitch.

**Comment by reedstrm** [comment]
Since Connexions/cnx-db#86 is now merged, I removed the :skull_and_crossbones: Let's see if they pass now

**Comment by karenc** [comment]
Yay the tests pass now :tada:

There was a problem with the archive container, it exited :o (https://travis-ci.org/Connexions/cnx-archive/builds/298931840#L2526).

I should probably get it to fail instead of keep on printing more stuff.

**Comment by karenc** [comment]
Yay the tests pass now :tada:

There was a problem with the archive container, it exited :o (https://travis-ci.org/Connexions/cnx-archive/builds/298931840#L2526).

I should probably get it to fail instead of keep on printing more stuff.

**Comment by karenc** [comment]
Yay the tests pass now :tada:

There was a problem with the archive container, it exited :o (https://travis-ci.org/Connexions/cnx-archive/builds/298931840#L2526).

I should probably get it to fail instead of keep on printing more stuff.

**Comment by karenc** [comment]
Yay the tests pass now :tada:

There was a problem with the archive container, it exited :o (https://travis-ci.org/Connexions/cnx-archive/builds/298931840#L2526).

I should probably get it to fail instead of keep on printing more stuff.

**Pull request merged**
