### PR TITLE
Pin the cnx-db docker container version and fix a test

### PR DESCRIPTION
**Pull request by pumazi**
The pinning seen here is similar to #548. See the discussion on that issue for details.

The test fix is because cnx-db has changed since the last successful test run. (We should also think about pinning against a released version of cnx-db, but one step at a time. This is something that is being done in Press and is working well.)

### CODE REVIEW

**Comment by reedstrm** [comment]
well, I did recently merge a change to cnx-db. Perhaps this means I should have updated/moved tests from cnx-archive?

**Comment by pumazi** [comment]
The effected test was closer to a functional test of the web api. So the failure here is correct.

**Comment by pumazi** [comment]
I'm actively adding/adjusting tests to reactively fix issues associated with cnx-db merges.

**Comment by pumazi** [comment]
I don't believe the cnx-db change to add a short-id works as expected. Looks like it paved over all the other info.
```diff
- {u'books': [{u'authors': u'55_943-0@7.1',
+ {u'books': [{u'authors': [{u'firstname': u'OpenStax College',
+                            u'fullname': u'OpenStax College',
+                            u'suffix': None,
+                            u'surname': None,
+                            u'title': None,
+                            u'username': u'OpenStaxCollege'}],
               u'ident_hash': u'e79ffde3-7fb4-4af3-9ec8-df648b391597@7.1',
               u'title': u'College Physics'},
-             {u'authors': u'pzPQ0t6b@1.1',
+             {u'authors': [{u'firstname': u'OpenStax College',
+                            u'fullname': u'OpenStax College',
+                            u'suffix': None,
+                            u'surname': None,
+                            u'title': None,
+                            u'username': u'OpenStaxCollege'}],
```
(diff coloration red=test results, green=expected at this time)

**Comment by pumazi** [comment]
@reedstrm, I was just going to bring this PR up to snuff by touching up the test. It would seem there is a slightly larger issue here. Can you please look over the recent PRs merge in cnx-db around this page-in-books change?

**Pull request merged**
