### PR TITLE
Added query to get a list of available languages in modules

### PR DESCRIPTION
**Pull request by hackthehackerman**

### CODE REVIEW

**Comment by reedstrm** [comment]
How about we extend that a bit, to count the kinds of content, as is done for subjects? And especially with counts, make this against the latest_modules table - the modules table has every version of everything that's ever been published.

https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/sql/get-subject-list.sql

Also, since this is just the SQL, mark the PR as [WIP]. The full PR should contain the python to use this under the /extras route.

**Comment by hackthehackerman** [comment]
okay.

**Comment by edwoodward** [comment]
Do you want the counts for future use? They will not be used on the Advanced Search page.

**Comment by reedstrm** [comment]
@ed yes

**Pull request closed without merging**
