### PR TITLE
Ensure json

### PR DESCRIPTION
**Pull request by reedstrm**
Seem plpy doesn't do as much auto-type conversion as psycopg2, so the simulated plpy in the tests didn't catch this case.

### CODE REVIEW

**Comment by pumazi** [comment]
Everything looks good. It's just that the tests aren't passing.

**Comment by reedstrm** [comment]
right - @pumazi any clue what might be causing that? I can't replicate it. The error happens when copying the settings collection during test setup. I'm at a lost to see how this is getting tripped.

**Comment by pumazi** [comment]
This is the same issue that is plaguing the other PRs. I'm looking into it, but having found anything yet.

**Comment by reedstrm** [comment]
I'd like this merge.d The code coverage metric is bogus for the size of the patch, and that it is mock code that's not covered, anyway.

**Pull request merged**
