### PR TITLE
Production pyramid merge

### PR DESCRIPTION
**Pull request by reedstrm**
merging the pyramid port from master to production

### CODE REVIEW

**Comment by pumazi** [comment]
We need to **rename the production branch to spike-1.6.x** and/or scrap the production branch altogether. If you insist on keeping a production branch, I would suggest you pave over (force push master onto) the existing production branch.

**Comment by reedstrm** [comment]
@pumazi would love too, but we still need the page# based ref, since we haven't gotten that fix approved for completion of development.

**Comment by reedstrm** [comment]
THe failed test above has this signature:

**Comment by reedstrm** [comment]
I'm treating this PR as documenting my rollout, so I'm going to merge it myself.

**Pull request merged**
