### PR TITLE
Set Cache-Control headers in archive

### PR DESCRIPTION
**Pull request by Dantemss**
Still need to test if the routes with multiple decorators will behave properly.

### CODE REVIEW

**Comment by reedstrm** [comment]
@mulich  - we merging this w/o the test, then?

**Comment by reedstrm** [comment]
@pumazi we merging w/o the test, then?

**Comment by pumazi** [comment]
I don't think we need to test the framework is doing the right thing with this info. So no tests necessary. 👍

**Comment by reedstrm** [comment]
Right. Meant to put that comment on the cnx-publishing Fallback PR.

**Pull request merged**
