### PR TITLE
Move module_files.mimetype to files.media_type

### PR DESCRIPTION
**Pull request by pumazi**
This puts the mime-type (aka media type and content type) on the files table.

This adds the db-migrator feature to this project. Please review this part of the pull request carefully.

### CODE REVIEW

**Comment by reedstrm** [comment]
Looking at legacy code, [https://github.com/Rhaptos/Products.RhaptosModuleStorage](Products.RhaptosModuleStorage) seems to treat the mime_type value as write only, so I think this is even a backwards-compatible change

**Comment by karenc** [comment]
:+1:

**Comment by karenc** [comment]
What happens when legacy wants to write to `module_files.mimetype`?  This PR removes the column right?

**Comment by reedstrm** [comment]
I'm preparing a matching PR for RhaptosModuleStorage, which will shift where the mimetype is stored, to match.

**Comment by pumazi** [comment]
I've split the migration in two. Have another look.

**Comment by karenc** [comment]
:+1:

FYI Now that there are two migrations, if you want to just run the first migration, you can do something like:

```
$ dbmigrator --context cnx-archive --config development.ini migrate --version=20160128110515
Running migration 20160128110515 mimetype_on_files_table                                                                                 
These files (fileid, sha1) do not have a corresponding module_files entry:                                                               
101, a5b4875b9e44ab9cf0332e4588af233d5657d131                                                                                            
                                                                                                                                         
---                                                                                                                                      
+++                                                                                                                                      
@@ -1458,21 +1458,22 @@                                                                                                                  
 ALTER TABLE public.document_hits OWNER TO cnxarchive;                                                                                   
                                                                                                                                         
 --                                                                                                                                      
 -- Name: files; Type: TABLE; Schema: public; Owner: cnxarchive; Tablespace:                                                             
 --                                                                                                                                      
                                                                                                                                         
 CREATE TABLE files (                                                                                                                    
     fileid integer NOT NULL,                                                                                                            
     md5 text,                                                                                                                           
     sha1 text,                                                                                                                          
-    file bytea                                                                                                                          
+    file bytea,                                                                                                                         
+    media_type text                                                                                                                     
 );                                                                                                                                      
                                                                                                                                         
                                                                                                                                         
 ALTER TABLE public.files OWNER TO cnxarchive;                                                                                           
                                                                                                                                         
 --                                                                                                                                      
 -- Name: files_fileid_seq; Type: SEQUENCE; Schema: public; Owner: cnxarchive                                                            
 --                                                                                                                                      
                                                                                                                                         
 CREATE SEQUENCE files_fileid_seq                                                                                                        
                                                          
```

**Comment by reedstrm** [comment]
Excellent!

**Pull request merged**
